### Array Information and Inspection:
- **Similar:**
  - `count()`
  - `sizeof()` (alias of `count()`)
  - `array_key_exists()`
  - `in_array()`
  - `array_search()`
  - `array_keys()`
  - `array_values()`
  - `array_column()`
  - `array_count_values()`
  - `array_key_first()`
  - `array_key_last()`
- **Different:**
  - `current()`
  - `each()` (deprecated)